import aptos from './assets/aptos-apt-logo.png'
import arbitrum from './assets/arbitrum-arb-logo.png'
import bitcoin from './assets/bitcoin-btc-logo.png'
import eigenlayer from './assets/eigenlayer-eigen-logo.png'
import ethereum from './assets/ethereum-eth-logo.png'
import sui from './assets/sui-sui-logo.png'

export const cryptoData = {
    result: [
        {
            id: "bitcoin",
            icon: bitcoin,
            name: "Bitcoin",
            symbol: 'BTC',
            rank: 1,
            price: 30000,
            priceBtc: 1,
            volume: 15000000000,
            marketCap: 500000000000,
            availableSupply: 19000000,
            totalSupply: 21000000,
            priceChange1h: -0.2,
            priceChange1d: 1.5,
            priceChange1w: 5.4,
            contractAddress: "bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf7ln0",
        },
        {
            id: "ethereum",
            icon: ethereum,
            symbol: 'ETH',
            name: "Ethereum",
            rank: 2,
            price: 1800,
            volume: 8000000000,
            marketCap: 220000000000,
            availableSupply: 120000000,
            totalSupply: null,
            priceChange1h: 0.1,
            priceChange1d: 2.3,
            priceChange1w: 4.8,
            contractAddress: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",

        },
        {
            id: "sui",
            icon: sui,
            name: "Sui",
            symbol: "SUI",
            rank: 50,
            price: 1,
            priceBtc: 0.000045,
            volume: 200000000,
            marketCap: 600000000,
            availableSupply: 500000000,
            totalSupply: 1000000000,
            priceChange1h: -0.1,
            priceChange1d: 3.5,
            priceChange1w: 7.2,
        },
        {
            id: "aptos",
            icon: aptos,
            name: "Aptos",
            symbol: "APT",
            rank: 30,
            price: 7.5,
            priceBtc: 0.00028,
            volume: 600000000,
            marketCap: 1500000000,
            availableSupply: 200000000,
            totalSupply: 1000000000,
            priceChange1h: 0.5,
            priceChange1d: -1.2,
            priceChange1w: 10.5,
            contractAddress: "0x1::aptos_coin::AptosCoin",
        },
        {
            id: "arbitrum",
            icon: arbitrum,
            name: "Arbitrum",
            symbol: "ARB",
            rank: 35,
            price: 1.15,
            priceBtc: 0.000042,
            volume: 450000000,
            marketCap: 1400000000,
            availableSupply: 1200000000,
            totalSupply: 10000000000,
            priceChange1h: -0.3,
            priceChange1d: 2.1,
            priceChange1w: 6.3,
        },
        {
            id: "eigenlayer",
            icon: eigenlayer,
            name: "EigenLayer",
            symbol: "EIGEN",
            rank: 45,
            price: 2.8,
            priceBtc: 0.000105,
            volume: 100000000,
            marketCap: 400000000,
            availableSupply: 150000000,
            totalSupply: 1000000000,
            priceChange1h: 0.2,
            priceChange1d: 4.2,
            priceChange1w: 8.7,
        }
    ]
};

export const cryptoAssets = [
    {
        id: 'bitcoin',
        amount: 0.02,
        price: 27000,
        date: new Date(),
    },
    {
        id: 'ethereum',
        amount: 1.5,
        price: 2000,
        date: new Date(),
    },
    {
        id: "sui",
        amount: 100,
        price: 2,
        date: new Date(),
    },
    {
        id: "aptos",
        amount: 50,
        price: 5,
        date: new Date(),
    },
    {
        id: "arbitrum",
        amount: 200,
        price: 1.15,
        date: new Date(),
    },
    {
        id: "eigenlayer",
        amount: 300,
        price: 2.8,
        date: new Date(),
    },
];
